http:
  routers:
    nginx-router:
      rule: "PathPrefix(`/nginx`)"
      service: nginx-service

  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: "http://nginx/"
