global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

log:
  level: DEBUG

providers:
  file:
    directory: /etc/traefik/fileprovider
    watch: true
