services:
  redis:
    image: redis:7

  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      DB_PATH: ./data/notes.db

